/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API aligned to busnau-api plan-v3 (TaskResponse/UserResponse DTOs, timestamps, paged lists, logout-all). Spec rebuilt 2026-08-07 from controllers + live JSON samples. Prefer re-export: curl -s http://localhost:8080/v3/api-docs (needs running app with openapi permitAll).
 * OpenAPI spec version: v2
 */

export interface CreateTaskRequest {
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  dueDate?: string | null;
  completed?: boolean;
  /**
   * Optional; ADMIN may assign to another user
   * @nullable
   */
  userId?: number | null;
}
