/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API. Synced from busnau-api controllers + live response shapes (2026-08-07). Live /v3/api-docs was blocked by security matcher (exact path); re-export after API fix when available.
 * OpenAPI spec version: v1
 */
import type { PageParameter } from './pageParameter';
import type { SizeParameter } from './sizeParameter';
import type { SortParameter } from './sortParameter';

export type GetAllUsersParams = {
/**
 * Zero-based page index
 * @minimum 0
 */
page?: PageParameter;
/**
 * Page size
 * @minimum 1
 */
size?: SizeParameter;
/**
 * Sorting criteria in the format: property(,asc|desc). Multiple sort params allowed.
 */
sort?: SortParameter;
};
