/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API aligned to busnau-api plan-v3 (TaskResponse/UserResponse DTOs, timestamps, paged lists, logout-all). Spec rebuilt 2026-08-07 from controllers + live JSON samples. Prefer re-export: curl -s http://localhost:8080/v3/api-docs (needs running app with openapi permitAll).
 * OpenAPI spec version: v2
 */
import type { PageableObject } from './pageableObject';
import type { SortObject } from './sortObject';
import type { Task } from './task';

export interface PageTask {
  content: Task[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
  numberOfElements?: number;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
  pageable?: PageableObject;
  sort?: SortObject;
}
