/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API. Synced from busnau-api controllers + live response shapes (2026-08-07). Live /v3/api-docs was blocked by security matcher (exact path); re-export after API fix when available.
 * OpenAPI spec version: v1
 */

export interface SortObject {
  empty?: boolean;
  sorted?: boolean;
  unsorted?: boolean;
}
