/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API aligned to busnau-api plan-v3 (TaskResponse/UserResponse DTOs, timestamps, paged lists, logout-all). Spec rebuilt 2026-08-07 from controllers + live JSON samples. Prefer re-export: curl -s http://localhost:8080/v3/api-docs (needs running app with openapi permitAll).
 * OpenAPI spec version: v2
 */

/**
 * TaskResponse DTO
 */
export interface Task {
  id: number;
  title: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  dueDate?: string | null;
  completed: boolean;
  /** @nullable */
  userId?: number | null;
  /** ISO-8601 instant */
  createdAt?: string;
  /** ISO-8601 instant */
  updatedAt?: string;
}
