/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * busnau-api
 * Task manager API. Synced from busnau-api controllers + live response shapes (2026-08-07). Live /v3/api-docs was blocked by security matcher (exact path); re-export after API fix when available.
 * OpenAPI spec version: v1
 */

/**
 * Partial update — null/omitted fields are left unchanged
 */
export interface UpdateTaskRequest {
  /** @nullable */
  title?: string | null;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  dueDate?: string | null;
  /** @nullable */
  completed?: boolean | null;
}
