/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRole } from './userRole';

export interface User {
  id?: number;
  username: string;
  role: UserRole;
}
