/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import {
  faker
} from '@faker-js/faker';

import {
  HttpResponse,
  delay,
  http
} from 'msw';
import type {
  RequestHandlerOptions
} from 'msw';

import type {
  Task,
  User
} from '@/lib/model';


export const getGetAllUsersResponseMock = (): User[] => (Array.from({
  length: faker.number.int({
    min: 1,
    max: 10
  })
}, (_, i) => i + 1).map(() => ({
  id: (() => faker.number.int({min: 1, max: 1000000}))(),
  username: faker.string.alpha({length: {min: 8, max: 32}}),
  role: faker.helpers.arrayElement(['ADMIN', 'USER'] as const)
})))

export const getCreateUserResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({
  id: (() => faker.number.int({
    min: 1,
    max: 1000000
  }))(),
  username: faker.string.alpha({length: {min: 8, max: 32}}),
  role: faker.helpers.arrayElement(['ADMIN', 'USER'] as const), ...overrideResponse
})

export const getGetAllTasksResponseMock = (): Task[] => (Array.from({
  length: faker.number.int({
    min: 1,
    max: 10
  })
}, (_, i) => i + 1).map(() => ({
  id: (() => faker.number.int({min: 1, max: 1000000}))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined])
})))

export const getCreateTaskResponseMock = (overrideResponse: Partial<Extract<Task, object>> = {}): Task => ({
  id: (() => faker.number.int({
    min: 1,
    max: 1000000
  }))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse
})

export const getRefreshTokenResponseMock = (): string => (faker.word.sample())

export const getAuthenticateUserResponseMock = (): string => (faker.word.sample())

export const getGetUserByIdResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({
  id: (() => faker.number.int({
    min: 1,
    max: 1000000
  }))(),
  username: faker.string.alpha({length: {min: 8, max: 32}}),
  role: faker.helpers.arrayElement(['ADMIN', 'USER'] as const), ...overrideResponse
})

export const getGetUserByUsernameResponseMock = (overrideResponse: Partial<Extract<User, object>> = {}): User => ({
  id: (() => faker.number.int({
    min: 1,
    max: 1000000
  }))(),
  username: faker.string.alpha({length: {min: 8, max: 32}}),
  role: faker.helpers.arrayElement(['ADMIN', 'USER'] as const), ...overrideResponse
})

export const getGetTaskByIdResponseMock = (overrideResponse: Partial<Extract<Task, object>> = {}): Task => ({
  id: (() => faker.number.int({
    min: 1,
    max: 1000000
  }))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined]), ...overrideResponse
})

export const getGetTasksByUserIdResponseMock = (): Task[] => (Array.from({
  length: faker.number.int({
    min: 1,
    max: 10
  })
}, (_, i) => i + 1).map(() => ({
  id: (() => faker.number.int({min: 1, max: 1000000}))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined])
})))

export const getGetTasksByUserIdAndDateRangeResponseMock = (): Task[] => (Array.from({
  length: faker.number.int({
    min: 1,
    max: 10
  })
}, (_, i) => i + 1).map(() => ({
  id: (() => faker.number.int({min: 1, max: 1000000}))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined])
})))

export const getGetTasksByCompletedResponseMock = (): Task[] => (Array.from({
  length: faker.number.int({
    min: 1,
    max: 10
  })
}, (_, i) => i + 1).map(() => ({
  id: (() => faker.number.int({min: 1, max: 1000000}))(),
  title: faker.string.alpha({length: {min: 8, max: 32}}),
  description: faker.helpers.arrayElement([faker.string.alpha({length: {min: 8, max: 32}}), undefined]),
  dueDate: faker.helpers.arrayElement([faker.date.past().toISOString().slice(0, 10), undefined]),
  completed: faker.helpers.arrayElement([faker.datatype.boolean(), undefined]),
  userId: faker.helpers.arrayElement([faker.number.int(), undefined])
})))


export const getGetAllUsersMockHandler = (overrideResponse?: User[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User[]> | User[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/users', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetAllUsersResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getCreateUserMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.post('*/api/users', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getCreateUserResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getGetAllTasksMockHandler = (overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/tasks', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetAllTasksResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getCreateTaskMockHandler = (overrideResponse?: Task | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<Task> | Task), options?: RequestHandlerOptions) => {
  return http.post('*/api/tasks', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getCreateTaskResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getRefreshTokenMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/refresh', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getRefreshTokenResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getAuthenticateUserMockHandler = (overrideResponse?: string | ((info: Parameters<Parameters<typeof http.post>[1]>[0]) => Promise<string> | string), options?: RequestHandlerOptions) => {
  return http.post('*/api/auth/login', async (info: Parameters<Parameters<typeof http.post>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getAuthenticateUserResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getGetUserByIdMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetUserByIdResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getDeleteUserMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/users/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }

    return new HttpResponse(null,
      {
        status: 204
      })
  }, options)
}

export const getGetUserByUsernameMockHandler = (overrideResponse?: User | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<User> | User), options?: RequestHandlerOptions) => {
  return http.get('*/api/users/username/:username', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetUserByUsernameResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getGetTaskByIdMockHandler = (overrideResponse?: Task | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task> | Task), options?: RequestHandlerOptions) => {
  return http.get('*/api/tasks/:id', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetTaskByIdResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getDeleteTaskMockHandler = (overrideResponse?: void | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Promise<void> | void), options?: RequestHandlerOptions) => {
  return http.delete('*/api/tasks/:id', async (info: Parameters<Parameters<typeof http.delete>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());
    if (typeof overrideResponse === 'function') {
      await overrideResponse(info);
    }

    return new HttpResponse(null,
      {
        status: 204
      })
  }, options)
}

export const getGetTasksByUserIdMockHandler = (overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/tasks/user/:userId', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetTasksByUserIdResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getGetTasksByUserIdAndDateRangeMockHandler = (overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/tasks/user/:userId/date-range', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetTasksByUserIdAndDateRangeResponseMock(),
      {
        status: 200
      })
  }, options)
}

export const getGetTasksByCompletedMockHandler = (overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]), options?: RequestHandlerOptions) => {
  return http.get('*/api/tasks/completed/:completed', async (info: Parameters<Parameters<typeof http.get>[1]>[0]) => {
    await delay((() => faker.number.int({min: 200, max: 800}))());


    return HttpResponse.json(overrideResponse !== undefined
        ? (typeof overrideResponse === "function" ? await overrideResponse(info) : overrideResponse)
        : getGetTasksByCompletedResponseMock(),
      {
        status: 200
      })
  }, options)
}
export const getOpenAPIDefinitionMock = () => [
  getGetAllUsersMockHandler(),
  getCreateUserMockHandler(),
  getGetAllTasksMockHandler(),
  getCreateTaskMockHandler(),
  getRefreshTokenMockHandler(),
  getAuthenticateUserMockHandler(),
  getGetUserByIdMockHandler(),
  getDeleteUserMockHandler(),
  getGetUserByUsernameMockHandler(),
  getGetTaskByIdMockHandler(),
  getDeleteTaskMockHandler(),
  getGetTasksByUserIdMockHandler(),
  getGetTasksByUserIdAndDateRangeMockHandler(),
  getGetTasksByCompletedMockHandler()
]
