/**
 * Generated by orval v8.5.2 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import axios from 'axios';
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CreateTaskRequest,
  CreateUserRequest,
  GetTasksByUserIdAndDateRangeParams,
  LoginRequest,
  RefreshRequest,
  Task,
  User
} from '@/lib/model';




  export const getOpenAPIDefinition = (axiosInstance: AxiosInstance = axios) => {
/**
 * @summary Get all users
 */
const getAllUsers = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User[]>> => {
    return axiosInstance.get(
      `/api/users`,options
    );
  }

/**
 * @summary Create a new user
 */
const createUser = (
    createUserRequest: CreateUserRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axiosInstance.post(
      `/api/users`,
      createUserRequest,options
    );
  }

/**
 * @summary Get all tasks
 */
const getAllTasks = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    return axiosInstance.get(
      `/api/tasks`,options
    );
  }

/**
 * @summary Create a new task
 */
const createTask = (
    createTaskRequest: CreateTaskRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task>> => {
    return axiosInstance.post(
      `/api/tasks`,
      createTaskRequest,options
    );
  }

/**
 * @summary Refresh access token
 */
const refreshToken = (
    refreshRequest: RefreshRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/api/auth/refresh`,
      refreshRequest,{
    ...options,}
    );
  }

/**
 * @summary Authenticate user
 */
const authenticateUser = (
    loginRequest: LoginRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<string>> => {
    return axiosInstance.post(
      `/api/auth/login`,
      loginRequest,{
    ...options,}
    );
  }

/**
 * @summary Get a user by ID
 */
const getUserById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axiosInstance.get(
      `/api/users/${id}`,options
    );
  }

/**
 * @summary Delete a user by ID
 */
const deleteUser = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/users/${id}`,options
    );
  }

/**
 * @summary Get a user by username
 */
const getUserByUsername = (
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<User>> => {
    return axiosInstance.get(
      `/api/users/username/${username}`,options
    );
  }

/**
 * @summary Get a task by ID
 */
const getTaskById = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task>> => {
    return axiosInstance.get(
      `/api/tasks/${id}`,options
    );
  }

/**
 * @summary Delete a task
 */
const deleteTask = (
    id: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    return axiosInstance.delete(
      `/api/tasks/${id}`,options
    );
  }

/**
 * @summary Get tasks by user ID
 */
const getTasksByUserId = (
    userId: number, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    return axiosInstance.get(
      `/api/tasks/user/${userId}`,options
    );
  }

/**
 * @summary Get tasks by user ID and date range
 */
const getTasksByUserIdAndDateRange = (
    userId: number,
    params: GetTasksByUserIdAndDateRangeParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    return axiosInstance.get(
      `/api/tasks/user/${userId}/date-range`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary Get tasks by completed status
 */
const getTasksByCompleted = (
    completed: boolean, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Task[]>> => {
    return axiosInstance.get(
      `/api/tasks/completed/${completed}`,options
    );
  }

return {getAllUsers,createUser,getAllTasks,createTask,refreshToken,authenticateUser,getUserById,deleteUser,getUserByUsername,getTaskById,deleteTask,getTasksByUserId,getTasksByUserIdAndDateRange,getTasksByCompleted}};
export type GetAllUsersResult = AxiosResponse<User[]>
export type CreateUserResult = AxiosResponse<User>
export type GetAllTasksResult = AxiosResponse<Task[]>
export type CreateTaskResult = AxiosResponse<Task>
export type RefreshTokenResult = AxiosResponse<string>
export type AuthenticateUserResult = AxiosResponse<string>
export type GetUserByIdResult = AxiosResponse<User>
export type DeleteUserResult = AxiosResponse<void>
export type GetUserByUsernameResult = AxiosResponse<User>
export type GetTaskByIdResult = AxiosResponse<Task>
export type DeleteTaskResult = AxiosResponse<void>
export type GetTasksByUserIdResult = AxiosResponse<Task[]>
export type GetTasksByUserIdAndDateRangeResult = AxiosResponse<Task[]>
export type GetTasksByCompletedResult = AxiosResponse<Task[]>
